import { QrController }  from "components/QrController"
import type { NextPage } from "next"
import Head              from "next/head"
import styles            from "styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>QR Fragments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon"
              href="/home/adele/projects/idea_fragments/qr_fragments/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>QR Fragments</h1>

        <QrController />
      </main>

      <footer className={styles.footer}>
        <div>Powered by{" "} IdeaFragments</div>
      </footer>
    </div>
  )
}

export default Home
